version: "3.9"
services:

  monitoring-app:
    build: .
    container_name: monitoring-app
    ports:
      - 8000:8000

  influxdb:
    image: influxdb:2.1
    container_name: influxdb
    ports:
      - 8086:8086
      - 8088:8088
    restart: unless-stopped

  grafana:
      image: grafana/grafana:8.2.6
      container_name: grafana
      ports:
        - 3000:3000
      restart: unless-stopped
