version: "3.9"
services:
  monitoring-app:
    build: .
    container_name: monitoring-app
    ports:
      - 8000:8000

  influxdb:
    image: influxdb:2.1
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=keenetic
      - DOCKER_INFLUXDB_INIT_BUCKET=keenetic
      - DOCKER_INFLUXDB_INIT_RETENTION=52w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin_token
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
    ports:
      - 8086:8086
      - 8088:8088
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
