{
 "title": "Keenetic router dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "System name",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keenetic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"keenetic-router\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sys-name\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "System up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keenetic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"keenetic-router\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sys-up-time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "System description",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"keenetic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"keenetic-router\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sys-descr\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "FastEthernet0/0 In Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"keenetic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net-ifaces\")\n  |> filter(fn: (r) => r[\"_field\"] == \"f0/0-in-pkts\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Net interfaces",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"keenetic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net-ifaces\")\n  |> filter(fn: (r) => r[\"_field\"] == \"netIface-info\")\n  |> unique()\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "FastEthernet0/0 Out Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"keenetic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net-ifaces\")\n  |> filter(fn: (r) => r[\"_field\"] == \"f0/0-out-pkts\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}